apiVersion: v1
kind: PersistentVolume
metadata:
  name: "${disk_label==""? _name : disk_label}"
  labels:
    vol-id: "${disk_label==""? _name : disk_label}"
spec:
  storageClassName: "${storage_class}"
  capacity:
    storage: ${disk_size}
  accessModes:
    - ReadWriteOnce
  ${disk_config}
