language: go
go:
- "1.10.x"
env:
  global:
  # Key for Gcloud Service account (decrypted in before_install)
  - TF_VAR_gcloud_creds=./google-account.json

before_install:
- make setup-env
- openssl aes-256-cbc -K ${encrypted_5d2b0dc7b104_key} -iv ${encrypted_5d2b0dc7b104_iv} -in ./test/usermirror-ci-key -out ./google-account.json -d

install:
- make check

script:
- make deploy

after_script:
- make destroy
