apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-components
  labels:
    um-component: prometheus
spec:
  selector:
    matchExpressions:
    - {key: um-component, operator: Exists}
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 15s
