apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      um-component: prometheus
  resources:
    requests:
      memory: 400Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "${storage_class}"
        accessModes:
        - ReadWriteOnce
        volumeName: "${disk_label==""? _name : disk_label}"
        resources:
          requests:
            storage: ${disk_size}
