apiVersion: v1
kind: Service
metadata:
  name: huv-secret-api
  labels:
    app: huv-secret-api
spec:
  type: ClusterIP
  ports:
  - name: secret-api
    targetPort: 8888
    port: 80
  selector:
    app: huv-secret-api
