apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: secret-store-psp
spec:
  privileged: false  # Prevents creation of privileged Pods
  defaultAddCapabilities:
    - IPC_LOCK
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
