apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-tunnel
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - ingresses
  - services
  - endpoints
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-tunnel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-tunnel
subjects:
- kind: ServiceAccount
  name: argo-tunnel
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-tunnel
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-tunnel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-tunnel
subjects:
- kind: ServiceAccount
  name: argo-tunnel
  namespace: default