apiVersion: v1
kind: Service
metadata:
 name: contour-metrics
 namespace: heptio-contour
 annotations:
  # This annotation puts the AWS ELB into "TCP" mode so that it does not
  # do HTTP negotiation for HTTPS connections at the ELB edge.
  # The downside of this is the remote IP address of all connections will
  # appear to be the internal address of the ELB. See docs/proxy-proto.md
  # for information about enabling the PROXY protocol on the ELB to recover
  # the original remote IP address.
   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
 labels:
   um-component: envoy
spec:
 ports:
 # Only listen for secure connections
 - port: 80
   name: metrics
   protocol: TCP
   targetPort: 8000
 - port: 8002
   name: envoy-metrics
   protocol: TCP
 selector:
   app: contour
